In [25]:
import numpy as np
b = np.arange(27).reshape((3,3,3))
print(b)
id(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


140199851573120

In [26]:
id(b.ravel())


140199851570000

In [ ]:
import numpy as np
x = np.arange(27).reshape((3,3,3))
print(x)


In [ ]:
y = b.flatten()
y

In [ ]:
x = np.arange(12).reshape(3,4)
print(x)

In [ ]:
# x.T
np.transpose(x)





In [4]:
a = np.arange(5)
print(a)
a < 2


[0 1 2 3 4]


array([ True,  True, False, False, False])

In [5]:
print(a)
(a<2) | (a>3)

[0 1 2 3 4]


array([ True,  True, False, False,  True])

In [ ]:
def exp (x):
    return x<3 or x>3


np.vectorize(exp)(a)

In [12]:
r = a<3

np.size(a[r])
a[r].size


3

In [14]:
s = np.arange(25)
#print(s)
print(np.sum(s < 10))
print(np.sum(s[s<10]))

10
45


In [21]:
import numpy as np

arr = np.arange(16).reshape(4, 4)

print(arr[arr %2 != 0])

np.sum(arr[arr %2 != 0])

[ 1  3  5  7  9 11 13 15]


64

In [30]:
a =  np.arange(9).reshape(3 , 3)
print(a)
b = np.arange(10,19).reshape(3,3)
print(b)
c = np.arange(20,29).reshape(3,3)
print(c)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [37]:
#np.hstack((a, b,c))
np.vstack((c, c , c))

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [38]:
np.concatenate((a , b) , axis = 1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [39]:
np.dstack((a , b , c))

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]],

       [[ 6, 16, 26],
        [ 7, 17, 27],
        [ 8, 18, 28]]])

In [40]:
sp = np.arange(12).reshape(3,4)

print(sp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
np.split(sp,2 , axis = 1)



[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
x = np.array([5,6,7,1,3,10,69,55,32]).reshape(3,3)
# x = np.arange(9).reshape(3,3)
print(x)
# x.min()
# x.max()
# x.argmin()
# x.argmax()
# x.min(axis = 0)
# x.std()
# x.prod()
# (x < 10).any()
# (x>10).all()