In [ ]:
#reading assignent#python data analysis 2nd addition

In [3]:
#ones_like
import numpy as np
#x=np.ones(12).reshape(2,6)
x=np.arange(12).reshape(2,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [2]:
y=np.ones_like(x)
y

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [4]:
full_arr=np.full((3,4),12)
full_arr

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [12]:
str_array=np.array(['sdfs','sfas','dsf'],dtype='string_')
str_array

array([b'sdfs', b'sfas', b'dsf'], dtype='|S4')

In [14]:
#2d
q=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
#3d
w=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
x=w[0].copy()
w[0]=12
print(w)
w[0]=x
print(w[1,0])
w

[[[12 12 12 12]
  [12 12 12 12]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
[ 9 10 11 12]


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [24]:
#broadcasting

array([    1,     2,     3,     4,     5,    12, 12321,    12,     9])

In [46]:
#boolean indexing
names=np.array(['bob','joe','will','bob','will','joe','joe'])
data=np.random.randn(7,4)
print(data)
data[names=='bob']
data[names!='bob']
#data[~(names=='bob')]
data[names=='bob',:2]
data[names=='bob',3]
mask=(names=='bob')|(names=='will')
data[mask]
data[data<0]=0
data[~(names=='joe')]=7
data

[[ 0.69362319 -0.89440983  0.62955017 -1.3154952 ]
 [-1.42201487  1.76777771  0.1913     -0.76807195]
 [-0.50988543  2.03525216 -1.20688426 -0.04074301]
 [-2.40381332 -1.39332144 -0.16441232  0.85622452]
 [ 1.27235382 -1.40065946 -1.87493233 -1.30071986]
 [-0.32681791 -0.69848114 -1.5144567   0.91525357]
 [-1.54824105 -0.11967311  0.44344589  0.11445771]]


array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.76777771, 0.1913    , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.91525357],
       [0.        , 0.        , 0.44344589, 0.11445771]])

In [47]:
#fancy indexing

In [55]:
#t=np.empty((8,4))
t=np.zeros((8,4))
for i in range(8):
    t[i]=i
print(t)
t[[4,5,0]]

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [0., 0., 0., 0.]])

In [59]:
y=np.arange(32).reshape(8,4)
print(y)
y[[1,3,5,7],[2,0,1,3]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 6, 12, 21, 31])

In [60]:
#Transposing arrays and Swapping axes
u=np.arange(15).reshape(3,5)
u.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [62]:
i=np.random.randn(6,3)
np.dot(i.T,i)#matrix multiplication

array([[11.34975315, -4.5651357 ,  2.93649924],
       [-4.5651357 , 11.69979497, -4.33327531],
       [ 2.93649924, -4.33327531,  7.01238366]])

In [66]:
o = np.arange (16).reshape ((2, 2, 4))

print(o)

x = o.transpose(1,0,2) 

print('\nthis is x\n', x)

arr = np.arange(24).reshape((2, 3, 4))

print('\narr\n',arr)

new_arr = arr.transpose(2, 0, 1)#transposing columns into 2 rows

print('\nnnew_arr\n',new_arr)





[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

this is x
 [[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]

arr
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

nnew_arr
 [[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]


In [67]:
o.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [68]:
#universal functions
a=2
np.exp(a)

7.38905609893065

In [70]:
p=np.arange(10)
np.sqrt(p)
np.exp(p)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [74]:
a=np.random.randn(8)
print(a,'\n')
s=np.random.randn(8)
print(s,'\n')
np.maximum(a,s)

[-2.22346875  0.20398073  0.05429308 -0.73325022 -0.80759333 -0.39327366
 -0.04259319 -0.5791981 ] 

[ 7.70569926e-01  8.11903711e-01  1.74054278e+00  5.06289636e-01
 -2.02992836e-01  4.35834452e-01 -3.66836300e-04 -7.90095908e-01] 



array([ 7.70569926e-01,  8.11903711e-01,  1.74054278e+00,  5.06289636e-01,
       -2.02992836e-01,  4.35834452e-01, -3.66836300e-04, -5.79198101e-01])

In [75]:
d=np.random.randn(8)*5
remainder,whole_part=np.modf(d)
print(remainder,'\n',whole_part)

[-0.10035894  0.84951425 -0.00419345  0.86430155 -0.2843931  -0.44668082
  0.24501618  0.16271337] 
 [-4.  1. -9.  3. -4. -3.  3.  3.]


In [78]:
#array-oriented programming with arrays
points=np.arange(-5,5,0.01)
xs,ys=np.meshgrid(points,points)
np.sqrt(xs**2+ys**2)

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [85]:
xarr=np.linspace(1.1,1.5,5)
yarr=np.linspace(2.1,2.5,5)
cond=np.array([True,False,True,False,True])
result=[(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
result1=np.where(cond,xarr,yarr)
print(result,'\n')
result1

[1.1, 2.2, 1.3, 2.4, 1.5] 



array([1.1, 2.2, 1.3, 2.4, 1.5])

In [88]:
d=np.random.randn(4,4)
#res=np.where(d>0,2,-2) or
res=np.where(d>0,2,d)#only +ve values set to 2
res

array([[ 2.        , -1.18516316, -0.19877977,  2.        ],
       [ 2.        ,  2.        , -0.21534542,  2.        ],
       [ 2.        ,  2.        , -0.16103163,  2.        ],
       [-0.1679294 , -0.43052981, -0.64652223,  2.        ]])

In [12]:
#mathematical and statistical methods
f=np.random.randn(5,4)
f.mean()
f.sum(axis=1)#row wise operation

array([ 1.4118647 , -1.94953814,  4.66999202, -3.89498399, -0.86814985])

In [16]:
g=np.arange(1,10).reshape(3,3)
g.cumsum(0)
g.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

In [19]:
#mthods for bools array
'''
.all()
.any()
'''
#sorting
'''
h=np.random.randn(6)
print(h,'\n',h.sort())
g=np.random.randn(4,3)
print(g)
print(g.sort(1))
'''
large_arr = np.random.randn(1000)
print('length of array ',len(large_arr))
l=large_arr[int(0.05 * len(large_arr))]
#quantile
large_arr.sort()
k=large_arr[int(0.05 * len(large_arr))] # 5% quantile
print(l,'\n',k)#Out[205]: -1.5311513550102103'''

length of array  1000
0.4442101099457304 
 -1.5220916252565106


In [24]:
#unique and other set logic
names=np.array(['bob','will','joe','bob','will','joe','bob','will','joe'])
np.unique(names)
ints=np.array([1,1,2,2,3,3,4,4])
np.unique(ints)
#python alternate
sorted(set(names))
np.in1d(ints,[1,2])

array([ True,  True,  True,  True, False, False, False, False])

In [28]:
#file input and output with arrays
arr=np.arange(10)
#np.save('normal_array',arr)
#np.load('normal_array.npy')
np.savez('normal_archive.npz',a=arr,b=arr)
arch=np.load('normal_archive.npz')
arch['b']
#for compression
np.savez_compressed()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#linear ALgebra
import numpy.linalg


In [4]:
X=np.random.randn(5,5)
mat=X.T.dot(X)
#np.linalg.inv(mat)
mat.dot(np.linalg.inv(mat))

array([[ 1.00000000e+00, -2.93205138e-16,  1.16020918e-15,
         2.37280154e-16,  8.05158462e-16],
       [ 4.73480419e-16,  1.00000000e+00,  1.56768606e-15,
         1.19015767e-16,  1.32973651e-15],
       [ 5.70726118e-18,  2.19348276e-16,  1.00000000e+00,
         7.70501119e-17,  7.80139492e-17],
       [ 3.09677783e-16,  8.28745335e-16,  2.53029014e-15,
         1.00000000e+00,  9.37060317e-16],
       [ 1.96720679e-16,  9.09909087e-16,  1.19209819e-15,
         3.64577090e-16,  1.00000000e+00]])

In [45]:
q,r=np.linalg.qr(mat)
r

array([[-0.90168188, -0.18474063,  1.46818003, -4.24578248, -5.87945011],
       [ 0.        , -4.84040506,  0.07129239,  3.72952023, -6.04580094],
       [ 0.        ,  0.        , -1.21689669,  1.68539516,  4.18196439],
       [ 0.        ,  0.        ,  0.        , -1.29454929, -5.45574878],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.87840077]])

In [1]:
from random import normalvariate
n=1000000
%timeit samples=[normalvariate(0,1) for _ in range(n)] 

1.58 s ± 122 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit np.random.normal(size=n)

69.3 ms ± 4.74 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
np.random.seed(1234)
np.random.randn(10)
np.random.seed(1234)
np.random.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [10]:
rng=np.random.RandomState

array([ 1.15003572,  0.99194602,  0.95332413, -2.02125482, -0.33407737,
        0.00211836,  0.40545341,  0.28909194,  1.32115819, -1.54690555])

array([-0.20264632, -0.65596934,  0.19342138,  0.55343891,  1.31815155,
       -0.46930528,  0.67555409, -1.81702723, -0.18310854,  1.05896919])