In [98]:
import numpy as np


In [99]:
a=np.arange(0,12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [100]:
b=np.arange(12,24).reshape(4,3)
b

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [101]:
a+b#elementary additon operation

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [102]:
b-a

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [103]:
b*a

array([[  0,  13,  28],
       [ 45,  64,  85],
       [108, 133, 160],
       [189, 220, 253]])

In [104]:
veca.vecb=abcos@
(i1,j1,k1)*(i2,j2,k2)
i1.(i2,j2,k2)

---------------------------
b/a

SyntaxError: invalid syntax (<ipython-input-104-dcfbaa433fa3>, line 1)

In [105]:
b/a

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[        inf, 13.        ,  7.        ],
       [ 5.        ,  4.        ,  3.4       ],
       [ 3.        ,  2.71428571,  2.5       ],
       [ 2.33333333,  2.2       ,  2.09090909]])

In [106]:
a@b#normal matrix multiplication

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [107]:
np.size(a)

12

In [108]:
np.size(a,1)

3

In [109]:
np.size(a,0)

4

In [110]:
(a<2)|(a>3)#or logic

array([[ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [111]:
def exp(x):
    return x<2 or x>3 #wont work correct

In [112]:
np.vectorize(exp)(a)#now work good

array([[ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [113]:
e=2
e

2

In [114]:
#r=a<3
a[a<3]

array([0, 1, 2])

In [115]:
np.size(a[a<3])

3

In [116]:
a[a<3].size

3

In [117]:
s=np.arange(25)
print(s)
print(np.sum(s<10))
print(np.sum(s[s<10]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
10
45


In [8]:
import numpy as np
s=np.arange(25)
print(np.sum(s[s%2!=0]),' odd')
print(np.sum(s[s%2==0]),' Even')

144  odd
156  Even


In [119]:
m.ravel(2) #to reshaping 2d to 1d

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


array([ 5, 10, 15, 20, 25,  6, 11, 16, 21, 26,  7, 12, 17, 22, 27,  8, 13,
       18, 23, 28,  9, 14, 19, 24, 29])

In [120]:
m.flattened(2)#creates new memory and then convert 2d  to 1d,,,use this most

AttributeError: 'numpy.ndarray' object has no attribute 'flattened'

In [121]:
#c=b.ravel(2)
id(b.ravel(2))

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  


3106825658416

In [122]:
flattened.shape=(3,3)

NameError: name 'flattened' is not defined

In [123]:
id(b.flatten(2))

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


3106825658976

In [124]:
id(b.ravel(2))

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


3106825570944

In [125]:
id(b.flatten(2))

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


3106825659136

In [126]:
flattened.transpose()

NameError: name 'flattened' is not defined

In [127]:
t=np.arange(25).reshape(5,5)
t


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [128]:
m=np.transpose(t)
m

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [129]:
#Assignment matrix multiplicative inverse
m=np.arange(5,30).reshape(5,5)
np.linalg.inv(m)
'''
dot(a, ainv) = dot(ainv, a) = eye(a.shape[0]).

a = np.array([[1., 2.], [3., 4.]])
>>> ainv = inv(a)
>>> np.allclose(np.dot(a, ainv), np.eye(2))
True
>>> np.allclose(np.dot(ainv, a), np.eye(2))
True
'''

'\ndot(a, ainv) = dot(ainv, a) = eye(a.shape[0]).\n\na = np.array([[1., 2.], [3., 4.]])\n>>> ainv = inv(a)\n>>> np.allclose(np.dot(a, ainv), np.eye(2))\nTrue\n>>> np.allclose(np.dot(ainv, a), np.eye(2))\nTrue\n'

In [130]:
t.T#same as above

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [131]:
#next topic Stacking

In [132]:
#concatenat 2 matix to create new matrix , horizontal stacking and vertical stacking
#vertical scaling may rows add ker rhha hai,,,horizontl stacking may column add ker raha hai
g=np.arange(12).reshape(4,3)
h=np.arange(24,36).reshape(4,3)
i=np.arange(36,48).reshape(4,3)

In [133]:
np.hstack((g,h,i))#we can also slice to get particular part to make a wanted stack

array([[ 0,  1,  2, 24, 25, 26, 36, 37, 38],
       [ 3,  4,  5, 27, 28, 29, 39, 40, 41],
       [ 6,  7,  8, 30, 31, 32, 42, 43, 44],
       [ 9, 10, 11, 33, 34, 35, 45, 46, 47]])

In [134]:
np.vstack((g,h,i))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47]])

In [135]:
np.concatenate((g,h),axis=1)

array([[ 0,  1,  2, 24, 25, 26],
       [ 3,  4,  5, 27, 28, 29],
       [ 6,  7,  8, 30, 31, 32],
       [ 9, 10, 11, 33, 34, 35]])

In [136]:
np.concatenate((g,h),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [137]:
np.dstack((g,h,i))
#np.column_stack()
#np.row_stack()

array([[[ 0, 24, 36],
        [ 1, 25, 37],
        [ 2, 26, 38]],

       [[ 3, 27, 39],
        [ 4, 28, 40],
        [ 5, 29, 41]],

       [[ 6, 30, 42],
        [ 7, 31, 43],
        [ 8, 32, 44]],

       [[ 9, 33, 45],
        [10, 34, 46],
        [11, 35, 47]]])

In [138]:
#sp=np.arange(12).reshape(4,3)
#np.split(sp,2,axis=0)
#a=np.arange(12).reshape(3,4)
#np.hsplit(a,4)
a=np.arange(12).reshape(3,4)
#np.hsplit(a,2)
print(a)
np.hsplit(a,[1,3])
#np.split(a,2,axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0],
        [4],
        [8]]), array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]), array([[ 3],
        [ 7],
        [11]])]

In [9]:
a=np.arange(12).reshape(4,3)
print(a)
#np.vsplit(a,4)
#np.vsplit(a,2)
np.vsplit(a,[1,3])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[array([[0, 1, 2]]), array([[3, 4, 5],
        [6, 7, 8]]), array([[ 9, 10, 11]])]

In [140]:
a=np.arange(27).reshape(3,3,3)
print(a)
np.dsplit(a,3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [141]:
w=np.arange(4)
r=np.arange(4)
np.column_stack((w,r))

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3]])

In [142]:
'''hsplit
vsplit
dsplit'''

'hsplit\nvsplit\ndsplit'

In [143]:
last page 79 learning_pandas
standard deviation direct ajayaga,mean direct ajayaga,variance
pandas(.summary sub samnay ajayaga)

SyntaxError: invalid syntax (<ipython-input-143-46d001012f04>, line 1)

In [144]:
a.prod()#product
a.cumsum()#cumulative sum
a.cumprod()
a.ll()
a.any()

AttributeError: 'numpy.ndarray' object has no attribute 'll'

In [145]:
a=np.arange(1,9)

print(a.mean(),a.std(),a.var())

print(a.sum(),a.prod())

print(a.cumsum(),a.cumprod())

b=np.arange(9).reshape(3,3)

print(b.ndim)

4.5 2.29128784747792 5.25
36 40320
[ 1  3  6 10 15 21 28 36] [    1     2     6    24   120   720  5040 40320]
2


In [6]:
my_list = ['apple', 'banana', 'grapes', 'pear']
counter_list1 = list(enumerate(my_list,1))
counter_list = list(enumerate(my_list))
print(counter_list1,' indexing on our choice')
print(counter_list,' orginal formation')


[(1, 'apple'), (2, 'banana'), (3, 'grapes'), (4, 'pear')]  indexing on our choice
[(0, 'apple'), (1, 'banana'), (2, 'grapes'), (3, 'pear')]  orginal formation


In [15]:
a=np.arange(9)
a[np.arange(8,-1,-1)]
a[np.arange(8,-1)]
a[9::-1]
a[::-1]
a[9:-1:-1]

array([], dtype=int32)